# Generated by Django 2.0.2 on 2018-04-07 18:03

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=140)),
                ('course', models.CharField(max_length=140)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.FileField(upload_to=core.models.user_directory_path)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_who_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
