# Generated by Django 2.0.2 on 2018-04-07 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_videodetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='current_video',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.VideoDetails'),
        ),
    ]
