# Generated by Django 2.0.2 on 2018-04-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_studentdetails_current_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='course',
            field=models.CharField(default='none', max_length=140),
        ),
        migrations.AlterField(
            model_name='teacherdetails',
            name='subject',
            field=models.CharField(default='none', max_length=140),
        ),
    ]
